'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MainPage

    '''<summary>
    '''lblReportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MainForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''bDataReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bDataReports As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bEventReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bEventReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bAlarmReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bAlarmReports As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTrendDataAlarmReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTrendDataAlarmReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCDUDeviceBateeryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCDUDeviceBateeryStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcursionReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcursionReport As Global.System.Web.UI.WebControls.Button
End Class
